### PR TITLE
Fix: Import Breakage on 2.2+

### LINKED ISSUE #1: Imports can sometimes break the build on Nim 2.2.0 or higher
`Error: cannot open file: sequtils` is an error that can sometimes appear on newer Nim releases when not importing `std` first on Nim 2.2.0+

### PR DESCRIPTION
**Pull request by thearchivalone**
Fixes: #1

### CODE REVIEW

File: src/usu.nim [hunk 1]
```diff
@@ -3,7 +3,10 @@
 
   A simple configuration language that places type burden on the file consumer.
 ]##
-import sequtils, sets, strutils
+when NimVersion >= "2.2.0":
+  import std/[sequtils, sets, strutils]
```
Comment (daylinmorgan) [inline src/usu.nim]: just replace it with this line no need to guard it on nim version:

```
import std/[sequtils, sets, strutils]
```

Comment (thearchivalone) [reply src/usu.nim]: Got it. Wasn’t sure if Nim 2.0 had something about it that you absolutely needed the original imports for.
